- name: replace acl config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
    - name: Delete device ACL configuration from provided ACL configuration
      cisco.asa.asa_acls:
        config:
          - acls:
            - name: www-outside
        state: deleted
