- name: gather firewall facts
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa
    subset: "all"

  tasks:
    - name: Gather facts
      cisco.asa.asa_facts:
        gather_network_resources: 
        - all
      register: gather

    - name: Print gathered facts
      debug:
        msg: "{{ gather }}"

