- name: gather firewall acls
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
    - name: Gather facts
      cisco.asa.asa_acls:
        state: gathered
      register: gather

    - name: Print gathered facts
      debug:
        msg: "{{ gather }}"

