- name: init acl config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: ansible.netcommon.enable
    ansible_become_pass: emergent
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.asa.asa

  roles:
    - init_acl_config
