- name: init firewall config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
    - name: create fw_hostname string
      set_fact:
        fw_hostname: "{{ inventory_hostname | replace('.', '-') }}"

    - name: set hostname
      cisco.asa.asa_config:
        lines:
        - hostname "{{ fw_hostname }}"
      
    - name: configure WEB interface
      cisco.asa.asa_config:
        lines:
        - nameif WEB
        - security-level 0
        - ip address 10.0.200.240 255.255.255.0
        - no shutdown
        parents: [interface GigabitEthernet0/1]
      register: web_interface

    - name: configure APP interface
      cisco.asa.asa_config:
        lines:
        - nameif APP
        - security-level 100
        - ip address 10.0.100.240 255.255.255.0
        - no shutdown
        parents: [interface GigabitEthernet0/0]
      register: app_interface

    - name: initial ACLs
      cisco.asa.asa_acls:
        state: replaced
        config:
          - acls:
            - name: test_access
              acl_type: extended
              aces:
                - grant: deny
                  line: 1
                  protocol: tcp
                  protocol_options:
                    tcp: true
                  source:
                    address: 192.0.2.0
                    netmask: 255.255.255.0
                  destination:
                    address: 192.0.3.0
                    netmask: 255.255.255.0
                    port_protocol:
                      eq: www
                  log: debugging

