- name: parse acl config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
  - name: Parse the commands for provided configuration
    cisco.asa.asa_acls:
      running_config: "{{ lookup('file', '_parsed.cfg') }}"
      state: parsed