- name: render acl config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
  - name: Rendered the input configuration
    cisco.asa.asa_acls:
      config:
        - acls:
          - name: test_access
            acl_type: extended
            aces:
              - grant: deny
                line: 1
                protocol: tcp
                protocol_options:
                  tcp: true
                source:
                  address: 192.0.2.0
                  netmask: 255.255.255.0
                destination:
                  address: 192.0.3.0
                  netmask: 255.255.255.0
                  port_protocol:
                    eq: www
                log: default
              - grant: deny
                line: 2
                protocol: icmp
                protocol_options:
                  icmp:
                    alternate_address: true
                source:
                  address: 198.51.100.0
                  netmask: 255.255.255.0
                destination:
                  address: 198.51.110.0
                  netmask: 255.255.255.0
                log: errors
          - name: test_R1_traffic
            acl_type: extended
            aces:
              - grant: deny
                line: 1
                protocol_options:
                  tcp: true
                source:
                  address: 2001:db8:0:3::/64
                  port_protocol:
                    eq: www
                destination:
                  address: 2001:fc8:0:4::/64
                  port_protocol:
                    eq: telnet   
      state: rendered