- name: replace acl config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
    - name: Replace device ACL configuration with provided ACL configuration
      cisco.asa.asa_acls:
        config:
          - acls:
            - name: www-inside
              acl_type: extended
              aces:
                - grant: permit
                  line: 1
                  protocol_options:
                    tcp: true
                  source:
                    address: 10.1.50.0
                    netmask: 255.255.255.0
                  destination:
                    any: true
                    port_protocol:
                      eq: www
                  log: errors
                - grant: permit
                  line: 2
                  protocol_options:
                    tcp: true
                  source:
                    address: 10.1.50.0
                    netmask: 255.255.255.0
                  destination:
                    any: true
                    port_protocol:
                      eq: ssh
                  log: errors
            - name: www-outside
              acl_type: extended
              aces:
                - grant: permit
                  line: 1
                  protocol_options:
                    tcp: true
                  source:
                    address: 129.6.128.0
                    netmask: 255.255.255.0
                  destination:
                    address: 10.1.50.0
                    netmask: 255.255.255.0
                    port_protocol:
                      eq: ssh
                  log: errors 
        state: replaced