- name: init firewall config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: emergent
    ansible_connection: network_cli
    ansible_network_os: asa

  tasks:
    - name: initial inside ACL
      asa_acl:
        lines:
          - access-list icmp-inside line 1 extended permit icmp any any log disable
        match: line
        replace: line                  