- name: initial inside ACL
  cisco.asa.asa_acls:
    config:
      acls:
        - name: icmp-inside
          acl_type: extended
          aces:
          - grant: permit
            line: 1
            protocol: icmp
            source:
              any: true
            destination:
              any: true
            log: disable
    state: merged